/* NEON SURVIVOR original arsenal expansion.  Data and combat live here so balancing remains isolated. */
const ARSENAL_TIER_LABEL={common:'일반',rare:'희귀',hero:'영웅',legend:'전설',mythic:'신화'};
const ORIGINAL_ARSENAL={
  pulse:{name:'펄스 부메랑',tier:'common',icon:'🪃',desc:'시선 방향 에너지 부메랑 · 귀환 타격',attack:'시선 방향으로 관통 부메랑을 던지고 귀환시 다시 타격',special:'나갈 때와 돌아올 때 각각 적을 관통',max:'트윈 펄스 · 양쪽 방향 동시 발사',cooldown:1.0,range:330,levels:[['크기 +15%',1,1],['관통 +1',1,2],['비행 거리 +25%',1.12,2],['부메랑 +1',1.12,3],['피해량 +30%',1.3,3]]},
  saw:{name:'톱니 드론',tier:'common',icon:'⚙',desc:'적에게 직접 접근하는 회전 톱날 드론',attack:'플레이어 주변을 돌다 가까운 적에게 돌진해 접촉 지속 피해',special:'탄환 없이 톱날 본체가 적을 베고 복귀',max:'분쇄 편대 · 여러 적을 나눠 추적',cooldown:.42,range:210,levels:[['톱날 속도 +20%',1,1],['톱날 크기 +20%',1.05,1],['지속 피해 +30%',1.35,1],['드론 +1',1.35,2],['지속 피해 +35%',1.8,2]]},
  magnet:{name:'자기장 발생기',tier:'common',icon:'🧲',desc:'적을 모았다가 밀어내는 제어형 자기장',attack:'주변 일반 적을 잠시 끌어당긴 후 바깥으로 밀어냄',special:'낮은 피해 대신 적 대형을 무너뜨림',max:'극성 붕괴 · 정지 후 강한 폭발',cooldown:2.35,range:155,levels:[['자기장 범위 +20%',1,1],['발동 간격 -15%',1,1],['밀쳐내기 +35%',1.05,1],['자기장 피해 +45%',1.45,1],['범위 +25%',1.45,1]]},
  prism:{name:'프리즘 파편',tier:'common',icon:'🔺',desc:'벽과 적에서 갈라지는 삼각 에너지 조각',attack:'전방 파편이 적 또는 벽에 닿으면 작은 파편으로 분열',special:'분열과 반사로 연쇄 타격',max:'프리즘 폭주 · 마지막 파편이 폭발',cooldown:.92,range:520,levels:[['분열 수 +1',1,1],['파편 피해 +25%',1.25,1],['반사 +1',1.25,1],['발사 파편 +1',1.25,2],['피해량 +35%',1.7,2]]},
  wire:{name:'네온 와이어',tier:'rare',icon:'🕸',desc:'가까운 적들을 잇는 연쇄 에너지 선',attack:'플레이어→근처 적→주변 적 순으로 와이어를 연결해 지속 피해',special:'적이 뭉칠수록 연결 수가 늘어남',max:'전류망 · 연결 적 처치시 전류 도약',cooldown:.38,range:285,levels:[['연결 +1',1,2],['와이어 피해 +25%',1.25,2],['연결 거리 +20%',1.25,3],['연결 +1',1.25,4],['피해량 +35%',1.7,4]]},
  orbital:{name:'궤도 포격기',tier:'rare',icon:'🛰',desc:'조준 후 떨어지는 지연 에너지 포격',attack:'무작위 적 위치에 표식을 남기고 잠시 뒤 궤도 포격',special:'강한 한 방, 긴 공격 주기',max:'궤도 융단폭격 · 다중 연속 포격',cooldown:2.05,range:170,levels:[['포격 반경 +20%',1,1],['포격 피해 +30%',1.3,1],['포격 +1',1.3,2],['조준 시간 -25%',1.3,2],['반경 +25%',1.3,2]]},
  mirror:{name:'반사 코어',tier:'hero',icon:'🪞',desc:'적 탄환을 일부 반사하는 에너지 거울',attack:'플레이어 주위를 회전하며 접촉 피해, 비낙하 탄환 일부 반사',special:'보스 낙하 공격은 반사하지 않음',max:'미러 필드 · 주기적으로 거울 원형 전개',cooldown:.52,range:102,levels:[['거울 +1',1,2],['회전 피해 +30%',1.3,2],['반사 확률 +15%',1.3,2],['거울 범위 +20%',1.3,2],['피해량 +35%',1.75,2]]},
  phase:{name:'위상 절단기',tier:'hero',icon:'🌀',desc:'0.5초 뒤 전방 공간을 베는 예고형 절단선',attack:'플레이어 앞에 선을 남긴 뒤 0.5초 후 공간 절단',special:'투사체가 아닌 지연형 선 공격',max:'교차 절단 · 서로 다른 두 절단선',cooldown:1.2,range:330,levels:[['절단 폭 +20%',1,1],['절단 피해 +30%',1.3,1],['예고 시간 -15%',1.3,1],['절단 거리 +25%',1.3,1],['피해량 +35%',1.75,1]]},
  gravity:{name:'중력 구체',tier:'legend',icon:'🌑',desc:'느리게 이동하며 적을 모으는 붕괴 구체',attack:'시선 방향으로 느린 구체를 보내 주변 적을 흡입한 뒤 붕괴',special:'흡입한 적 수가 많을수록 마지막 붕괴가 강함',max:'중력 붕괴 · 흡입 수 비례 추가 피해',cooldown:2.6,range:220,levels:[['흡입 범위 +20%',1,1],['구체 지속 +25%',1,1],['붕괴 피해 +30%',1.3,1],['이동 속도 +20%',1.3,1],['범위 +25%',1.3,1]]},
  eye:{name:'심판의 눈',tier:'mythic',icon:'👁',desc:'표식 후 동시 판결을 내리는 홀로그램 눈',attack:'뒤쪽의 눈이 적을 스캔·표식하고 잠시 뒤 표식 모두에 에너지 낙하',special:'엘리트 추가 피해 · 보스 표식 중첩',max:'최종 판결 · 드물게 전장을 어둡게 하는 다중 판결',cooldown:2.85,range:520,levels:[['표식 대상 +1',1,2],['판결 피해 +25%',1.25,2],['표식 시간 -15%',1.25,3],['엘리트 판결 +40%',1.25,3],['대상 +2 · 피해 +30%',1.65,5]]}
};
const arsenalByName=Object.fromEntries(Object.entries(ORIGINAL_ARSENAL).map(([id,data])=>[data.name,{...data,id}]));
const arsenalWorld={entities:[],links:[],drones:[],flash:0,lastWeapon:'',mirrorCd:0};
const arsenalIcon=(item)=>arsenalByName[item?.name]?.icon||null;
function arsenalWeapon(){return arsenalByName[equipped?.weapon?.name]}
function arsenalLevel(w){return Math.max(1,Math.min(5,player?.weaponLevels?.[w.name]||1))}
function arsenalEvolved(){return !!player?.weaponEvolved}
function arsenalDamage(w,mult=1){const tier=['common','rare','hero','legend','mythic'].indexOf(w.tier),lv=arsenalLevel(w);return player.damage*(1+tier*.33)*(1+(lv-1)*.18)*(arsenalEvolved()?1.58:1)*mult}
function arsenalStat(w){const lv=arsenalLevel(w),row=w.levels[lv-1];return{lv,damage:arsenalDamage(w,row[1]),count:row[2],range:w.range*(1+(lv-1)*.09),cooldown:w.cooldown*(arsenalEvolved()?.72:1)}}
function arsenalSpawn(type,data){arsenalWorld.entities.push({type,age:0,hit:{},...data})}
function arsenalHit(e,damage,hit,limit=1){if(!e||!enemies.includes(e)||hit[e.id])return false;hit[e.id]=true;hurt(e,damage);return --limit<=0}
function arsenalBurst(px,py,r,damage,col='#8ff6ff'){effects.push({kind:'blast',x:px,y:py,l:.32,r,damage});burst(px,py,col,12)}
function arsenalFire(w,dt){
  const st=arsenalStat(w),aim=movementAim,damage=st.damage;
  if(w.id==='pulse'){const count=arsenalEvolved()?2:st.count;for(let i=0;i<count;i++){const a=arsenalEvolved()?aim+(i?Math.PI:0):aim+(i-(count-1)/2)*.16;arsenalSpawn('pulse',{x:player.x,y:player.y,vx:Math.cos(a)*520,vy:Math.sin(a)*520,range:st.range,damage,r:18+st.lv*3,pierce:2+st.lv,returning:false})}}
  if(w.id==='saw'){arsenalWorld.sawWanted=st.count;arsenalWorld.sawDamage=damage*.52;}
  if(w.id==='magnet'){arsenalSpawn('magnet',{x:player.x,y:player.y,r:st.range,damage:damage*.34,push:140+st.lv*38,phase:0});}
  if(w.id==='prism'){for(let i=0;i<st.count;i++){let a=aim+(i-(st.count-1)/2)*.16;arsenalSpawn('prism',{x:player.x,y:player.y,vx:Math.cos(a)*480,vy:Math.sin(a)*480,damage,r:12+st.lv*2,split:st.lv,life:2.1,bounces:st.lv+1})}}
  if(w.id==='wire')arsenalWorld.wire={damage:damage*.32,count:st.count,range:st.range,evolved:arsenalEvolved(),tick:0};
  if(w.id==='orbital'){let pool=enemies.filter(e=>!e.boss);if(!pool.length)pool=enemies;for(let i=0;i<st.count;i++){const e=pool[Math.floor(Math.random()*pool.length)];if(e)arsenalSpawn('orbital',{x:e.x,y:e.y,delay:Math.max(.26,.74-(st.lv-1)*.08),r:st.range,damage})}}
  if(w.id==='mirror'){arsenalWorld.mirrorWanted=st.count;arsenalWorld.mirrorDamage=damage*.38;}
  if(w.id==='phase'){for(let i=0;i<(arsenalEvolved()?2:1);i++){let a=aim+(i?Math.PI/2:0);arsenalSpawn('phase',{x:player.x+Math.cos(a)*st.range*.46,y:player.y+Math.sin(a)*st.range*.46,a,delay:Math.max(.28,.5-(st.lv-1)*.03),length:st.range,width:24+st.lv*5,damage})}}
  if(w.id==='gravity')arsenalSpawn('gravity',{x:player.x,y:player.y,vx:Math.cos(aim)*75*(1+(st.lv-1)*.05),vy:Math.sin(aim)*75*(1+(st.lv-1)*.05),r:st.range,damage,life:1.35+(st.lv-1)*.22,pulled:0});
  if(w.id==='eye'){const pool=[...enemies].sort((a,b)=>Math.hypot(a.x-player.x,a.y-player.y)-Math.hypot(b.x-player.x,b.y-player.y)).slice(0,st.count);arsenalSpawn('eye',{targets:pool.map(e=>e.id),delay:Math.max(.32,.85-(st.lv-1)*.08),damage,count:st.count,final:arsenalEvolved()});}
}
function arsenalUpdate(now){const dt=Math.min(.04,(now-(arsenalUpdate.last||now))/1000);arsenalUpdate.last=now;if(run&&!paused&&player){
  const w=arsenalWeapon();
  if(w){
    if(w.id==='saw'){const wanted=arsenalWorld.sawWanted||1;for(let i=arsenalWorld.drones.length;i<wanted;i++)arsenalWorld.drones.push({a:Math.random()*7,x:player.x,y:player.y,hit:{},hitCd:0});if(arsenalWorld.drones.length>wanted)arsenalWorld.drones.length=wanted;}
    if(w.id==='mirror'){const wanted=arsenalWorld.mirrorWanted||1;arsenalWorld.mirrors=arsenalWorld.mirrors||[];for(let i=arsenalWorld.mirrors.length;i<wanted;i++)arsenalWorld.mirrors.push({a:Math.random()*7,hit:{},hitCd:0});if(arsenalWorld.mirrors.length>wanted)arsenalWorld.mirrors.length=wanted;}
    if(w.id==='wire'&&arsenalWorld.wire){let info=arsenalWorld.wire;info.tick-=dt;if(info.tick<=0){info.tick=.22;let chain=[],remaining=[...enemies],prev={x:player.x,y:player.y};for(let n=0;n<info.count;n++){let next=remaining.sort((a,b)=>Math.hypot(a.x-prev.x,a.y-prev.y)-Math.hypot(b.x-prev.x,b.y-prev.y))[0];if(!next||Math.hypot(next.x-prev.x,next.y-prev.y)>info.range)break;chain.push(next);remaining=remaining.filter(e=>e!==next);prev=next;}arsenalWorld.links=chain;for(const e of chain){e._arsenalWire=true;hurt(e,info.damage);}}}
    if(w.id==='eye')arsenalWorld.eyeAngle=(arsenalWorld.eyeAngle||0)+dt*.7;
  }
  for(const d of arsenalWorld.drones){d.a+=dt*(2.1+(arsenalLevel(w||ORIGINAL_ARSENAL.saw)-1)*.18);const targetEnemy=target();const orbitX=player.x+Math.cos(d.a)*78,orbitY=player.y+Math.sin(d.a)*56;let tx=orbitX,ty=orbitY;if(targetEnemy&&Math.hypot(targetEnemy.x-player.x,targetEnemy.y-player.y)<290){tx=targetEnemy.x;ty=targetEnemy.y}d.x+=(tx-d.x)*Math.min(1,dt*2.1);d.y+=(ty-d.y)*Math.min(1,dt*2.1);d.hitCd-=dt;for(const e of [...enemies])if(Math.hypot(e.x-d.x,e.y-d.y)<e.r+20&&d.hitCd<=0){hurt(e,arsenalWorld.sawDamage||18);d.hitCd=.17;burst(d.x,d.y,'#a6f6ff',3)}}
  for(const m of arsenalWorld.mirrors||[]){m.a+=dt*2.6;m.x=player.x+Math.cos(m.a)*88;m.y=player.y+Math.sin(m.a)*62;m.hitCd-=dt;for(const e of [...enemies])if(Math.hypot(e.x-m.x,e.y-m.y)<e.r+15&&m.hitCd<=0){hurt(e,arsenalWorld.mirrorDamage||20);m.hitCd=.25}for(const s of enemyShots)if(!s.meteor&&!s.arsenalReflected&&Math.hypot(s.x-m.x,s.y-m.y)<30){s.arsenalReflected=true;s.l=0;const t=target();if(t){const a=Math.atan2(t.y-m.y,t.x-m.x);arsenalSpawn('reflect',{x:m.x,y:m.y,vx:Math.cos(a)*600,vy:Math.sin(a)*600,life:1.1,damage:arsenalWorld.mirrorDamage*2,r:8})}}}
  for(let i=arsenalWorld.entities.length-1;i>=0;i--){const q=arsenalWorld.entities[i];q.age+=dt;
    if(q.type==='pulse'){const dist=Math.hypot(q.x-player.x,q.y-player.y);if(!q.returning&&(dist>=q.range||q.age>.72)){q.returning=true;q.hit={}}if(q.returning){const u=unit(player.x-q.x,player.y-q.y);q.vx+=(u.x*640-q.vx)*Math.min(1,dt*6);q.vy+=(u.y*640-q.vy)*Math.min(1,dt*6)}q.x+=q.vx*dt;q.y+=q.vy*dt;for(const e of [...enemies])if(arsenalHit(e,q.damage,q.hit,q.pierce))q.age=4;if(q.age>2.2||(q.returning&&dist<28))q.dead=true}
    if(q.type==='prism'||q.type==='reflect'){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;const out=q.x<8||q.x>W-8||q.y<8||q.y>H-8;if(out&&q.type==='prism'&&q.bounces-->0){if(q.x<8||q.x>W-8)q.vx*=-1;if(q.y<8||q.y>H-8)q.vy*=-1}for(const e of [...enemies])if(!q.hit[e.id]&&Math.hypot(e.x-q.x,e.y-q.y)<e.r+q.r){q.hit[e.id]=true;hurt(e,q.damage);if(q.type==='prism'&&q.split>0){for(const turn of [-.48,.48]){const a=Math.atan2(q.vy,q.vx)+turn;arsenalSpawn('prism',{x:q.x,y:q.y,vx:Math.cos(a)*390,vy:Math.sin(a)*390,damage:q.damage*.62,r:Math.max(6,q.r*.75),split:q.split-1,life:1.15,bounces:1})}q.dead=true}else q.dead=true}if(q.life<=0){if(q.type==='prism'&&arsenalEvolved())arsenalBurst(q.x,q.y,42,q.damage*.5,'#bc7cff');q.dead=true}}
    if(q.type==='magnet'){q.phase+=dt;for(const e of enemies.filter(e=>!e.boss&&!e.elite)){let d=Math.hypot(e.x-q.x,e.y-q.y)||1;if(d<q.r){let u=unit(e.x-q.x,e.y-q.y);if(q.phase<.32){e.x-=u.x*150*dt;e.y-=u.y*150*dt}else if(q.phase<.58){e.x+=u.x*q.push*dt; e.y+=u.y*q.push*dt;hurt(e,q.damage*dt)}}}if(q.phase>.58){if(arsenalEvolved())arsenalBurst(q.x,q.y,q.r*.72,q.damage*4,'#9b7bff');q.dead=true}}
    if(q.type==='orbital'){q.delay-=dt;if(q.delay<=0){arsenalBurst(q.x,q.y,q.r,q.damage,'#79efff');q.dead=true}}
    if(q.type==='phase'){q.delay-=dt;if(q.delay<=0){const ex=q.x+Math.cos(q.a)*q.length*.5,ey=q.y+Math.sin(q.a)*q.length*.5;for(const e of [...enemies]){const rx=e.x-q.x,ry=e.y-q.y,along=rx*Math.cos(q.a)+ry*Math.sin(q.a),side=Math.abs(-rx*Math.sin(q.a)+ry*Math.cos(q.a));if(Math.abs(along)<q.length*.5&&side<q.width+e.r)hurt(e,q.damage)}arsenalBurst(q.x,q.y,q.width*2,q.damage*.12,'#d08dff');q.cut=true;q.dead=true}}
    if(q.type==='gravity'){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;for(const e of enemies){let d=Math.hypot(e.x-q.x,e.y-q.y)||1;if(d<q.r){let u=unit(q.x-e.x,q.y-e.y);e.x+=u.x*125*dt;e.y+=u.y*125*dt;q.pulled+=dt*.25;hurt(e,q.damage*.08*dt)}}if(q.life<=0){arsenalBurst(q.x,q.y,q.r,q.damage*(arsenalEvolved()?1+Math.min(1.2,q.pulled*.15):1),'#6e4fba');q.dead=true}}
    if(q.type==='eye'){q.delay-=dt;if(q.delay<=0){for(const id of q.targets){const e=enemies.find(v=>v.id===id);if(!e)continue;e._eyeMarks=(e._eyeMarks||0)+1;const bonus=e.boss?1+e._eyeMarks*.18:e.elite?1.55:1;arsenalBurst(e.x,e.y,46,q.damage*bonus,'#f6c4ff')}if(q.final){arsenalWorld.flash=.42;for(const e of [...enemies].filter(e=>!q.targets.includes(e.id)).slice(0,Math.max(2,q.count-1)))arsenalBurst(e.x,e.y,36,q.damage*.65,'#ffd45d')}q.dead=true}}
    if(q.dead)arsenalWorld.entities.splice(i,1);
  }
  arsenalWorld.flash=Math.max(0,arsenalWorld.flash-dt);
}requestAnimationFrame(arsenalUpdate)}
function arsenalDraw(){if(run&&player){
  for(const q of arsenalWorld.entities){x.save();x.translate(q.x||player.x,q.y||player.y);if(q.type==='pulse'){x.rotate(Math.atan2(q.vy,q.vx));x.strokeStyle='#72f4ff';x.shadowBlur=15;x.shadowColor='#52bfff';x.lineWidth=7;x.beginPath();x.arc(0,0,q.r,-1.2,1.2);x.stroke()}if(q.type==='prism'){x.rotate(Math.atan2(q.vy,q.vx));x.fillStyle='#ff9cff';x.shadowBlur=12;x.shadowColor='#7eefff';x.beginPath();x.moveTo(q.r,0);x.lineTo(-q.r*.8,-q.r*.65);x.lineTo(-q.r*.8,q.r*.65);x.closePath();x.fill()}if(q.type==='reflect'){x.fillStyle='#b8fbff';x.shadowBlur=10;x.shadowColor='#73edff';x.fillRect(-q.r,-q.r*.45,q.r*2,q.r*.9)}if(q.type==='magnet'){x.strokeStyle=q.phase<.32?'#79eaff':'#ff93df';x.lineWidth=4;x.globalAlpha=.65;x.beginPath();x.arc(0,0,q.r,0,7);x.stroke()}if(q.type==='orbital'){x.strokeStyle='#8df4ff';x.lineWidth=3;x.beginPath();x.arc(0,0,q.r*.42+Math.sin(q.age*16)*4,0,7);x.stroke();x.fillStyle='#bdfaff';x.fillRect(-10,-1,20,2)}if(q.type==='phase'){x.rotate(q.a);x.strokeStyle=q.cut?'#fff2ff':'#cc7cff';x.globalAlpha=q.cut?1:.7;x.lineWidth=q.width*.22;x.beginPath();x.moveTo(-q.length*.5,0);x.lineTo(q.length*.5,0);x.stroke()}if(q.type==='gravity'){x.fillStyle='#10051f';x.shadowBlur=24;x.shadowColor='#9758ff';x.beginPath();x.arc(0,0,26,0,7);x.fill();x.strokeStyle='#b36dff';x.lineWidth=3;x.beginPath();x.arc(0,0,34,0,7);x.stroke()}x.restore()}
  if(arsenalWorld.wire&&arsenalWorld.links.length){x.save();x.strokeStyle='#50f5ff';x.shadowBlur=12;x.shadowColor='#4ce3ff';x.lineWidth=4;x.beginPath();x.moveTo(player.x,player.y);for(const e of arsenalWorld.links)x.lineTo(e.x,e.y);x.stroke();x.restore()}
  for(const d of arsenalWorld.drones){x.save();x.translate(d.x,d.y);x.rotate(time*10);x.fillStyle='#b8eaff';x.shadowBlur=14;x.shadowColor='#5ef5ff';x.beginPath();x.arc(0,0,18,0,7);x.fill();x.fillStyle='#142d45';x.beginPath();x.arc(0,0,9,0,7);x.fill();for(let k=0;k<8;k++){x.rotate(Math.PI/4);x.fillStyle='#8ffcff';x.fillRect(13,-3,10,6)}x.restore()}
  for(const m of arsenalWorld.mirrors||[]){x.save();x.translate(m.x,m.y);x.rotate(m.a);x.fillStyle='#bffbff99';x.shadowBlur=15;x.shadowColor='#7df2ff';x.fillRect(-7,-20,14,40);x.strokeStyle='#e6ffff';x.strokeRect(-7,-20,14,40);x.restore()}
  const w=arsenalWeapon();if(w){x.save();x.translate(player.x,player.y-50);if(w.id==='eye'){x.translate(-Math.cos(movementAim)*26,-25);x.rotate(arsenalWorld.eyeAngle||0);x.strokeStyle='#ffd45d';x.fillStyle='#a56aff';x.shadowBlur=18;x.shadowColor='#d86cff';x.lineWidth=4;x.beginPath();x.ellipse(0,0,27,15,0,0,7);x.fill();x.stroke();x.fillStyle='#73f4ff';x.beginPath();x.ellipse(0,0,9,13,0,0,7);x.fill()}else{x.fillStyle='#72edff';x.font='bold 27px sans-serif';x.textAlign='center';x.fillText(w.icon,0,0)}x.restore()}
  if(arsenalWorld.flash){x.save();x.fillStyle=`rgba(8,2,26,${arsenalWorld.flash*.55})`;x.fillRect(0,0,W,H);x.restore()}
}requestAnimationFrame(arsenalDraw)}
function arsenalCard(w){const lv=arsenalLevel(w),evo=lv>=5&&!arsenalEvolved(),next=w.levels[Math.min(4,lv)],b=document.createElement('button');b.className=`upgrade-card arsenal-upgrade ${w.tier}`;b.innerHTML=`<span class="icon">${w.icon}</span><b>${evo?w.max:w.name}</b><small>${evo?`무기 최대 강화 · ${w.max}`:`무기 강화 · LV.${lv+1} / 5<br>${next[0]}`}</small>`;b.onclick=()=>{player.weaponLevels||={};if(evo){player.weaponEvolved=true;pop(`${w.max} 활성화!`)}else{player.weaponLevels[w.name]=lv+1;pop(`${w.name} LV.${lv+1} 강화!`)}paused=false;ui.up.classList.add('hidden')};return b}
function decorateOriginalWeapons(){for(const w of Object.values(arsenalByName))if(!weapons.some(item=>item.name===w.name))weapons.push({name:w.name,tier:w.tier,desc:w.desc,slot:'weapon',arsenalId:w.id});}
function recordDiscovery(item){try{const found=JSON.parse(localStorage.neonCodexDiscoveries||'{}'),key=`weapons:${item.name}`;if(!found[key]){found[key]=Date.now();localStorage.neonCodexDiscoveries=JSON.stringify(found);const unread=JSON.parse(localStorage.neonCodexUnread||'[]');if(!unread.includes(key)){unread.push(key);localStorage.neonCodexUnread=JSON.stringify(unread)}}}catch(_){}}
function legacyWeaponInfo(item){return{name:item.name,tier:item.tier||'common',icon:itemIcon(item),attack:item.desc||'장착 무기 고유 공격',damage:'요원 공격력 기반',cooldown:'무기별 자동 공격',range:'무기별',count:'무기별',special:'장착한 무기만 전투에서 자동 공격',max:'5성 강화 후 무기 돌파'}}
function openWeaponDetail(item){if(!item||item.slot!=='weapon')return;const w=arsenalByName[item.name],stats=w&&player?arsenalStat(w):null,info=w?{...w,lv:stats?.lv||1,damage:stats?.damage||'요원 공격력 기반',count:stats?.count||1,range:stats?.range||w.range,cooldown:stats?.cooldown||w.cooldown}:legacyWeaponInfo(item),next=w&&info.lv<5?w.levels[info.lv][0]:w&&!arsenalEvolved()?w.max:'최대 강화 완료';let modal=document.querySelector('#weapon-detail');if(!modal){modal=document.createElement('section');modal.id='weapon-detail';modal.className='weapon-detail hidden';document.body.append(modal)}modal.innerHTML=`<button class="weapon-detail-close">×</button><div class="weapon-detail-icon ${info.tier}">${info.icon}</div><div><p class="label">WEAPON ANALYSIS</p><h2>${info.name}</h2><b class="${info.tier}">${ARSENAL_TIER_LABEL[info.tier]}</b> <small>LV.${info.lv||1}</small></div><dl><dt>공격 방식</dt><dd>${info.attack}</dd><dt>피해량</dt><dd>${typeof info.damage==='number'?Math.round(info.damage):info.damage}</dd><dt>공격 주기</dt><dd>${typeof info.cooldown==='number'?`${info.cooldown.toFixed(2)}초`:info.cooldown}</dd><dt>범위</dt><dd>${typeof info.range==='number'?Math.round(info.range):info.range}</dd><dt>투사체 / 대상</dt><dd>${info.count||'1'}</dd><dt>특수 효과</dt><dd>${info.special}</dd><dt>다음 강화</dt><dd>${next}</dd><dt>MAX 미리보기</dt><dd>${info.max}</dd></dl>`;modal.querySelector('.weapon-detail-close').onclick=()=>modal.classList.add('hidden');modal.classList.remove('hidden')}
function renderWeaponAnalysis(){let root=document.querySelector('#weapon-analysis');if(!root){root=document.createElement('button');root.id='weapon-analysis';root.className='weapon-analysis';const equipment=document.querySelector('#equipment .equipment-actions');equipment?.insertAdjacentElement('afterend',root)}const item=equipped.weapon;if(!item){root.textContent='무기 분석 · 장착한 무기가 없습니다';return}const w=arsenalByName[item.name],lv=w&&player?arsenalLevel(w):1;root.innerHTML=`<span>${arsenalIcon(item)||itemIcon(item)}</span><b>${item.name}</b><small>${ARSENAL_TIER_LABEL[item.tier]||'일반'} · LV.${lv} · 상세 정보</small>`;root.onclick=()=>openWeaponDetail(item)}
function addCrateDecor(){const shop=document.querySelector('#shop');if(!shop||document.querySelector('#arsenal-crate-controls'))return;for(const [id,kind,icon,label] of [['buy-weapon','weapon','⚔','무기'],['buy-armor','armor','🛡','장비'],['buy-operative','operative','◈','요원']]){const b=document.getElementById(id);if(b){b.classList.add('arsenal-crate-card',`${kind}-crate`);b.innerHTML=`<span class="crate-art ${kind}"><i></i><b>${icon}</b></span><strong>${label} 상자</strong><small>${kind==='operative'?'🔑 또는 500 🪙':'100 🪙'}</small>`}}
  const controls=document.createElement('div');controls.id='arsenal-crate-controls';controls.innerHTML='<button class="crate-open-button weapon-open" data-open="weapon"><i>Ⅰ</i><span>무기 보급</span><small>단일 신호 해제</small><em>100 🪙</em></button><button class="crate-open-button weapon-open ten" data-open="weapon10"><i>×10</i><span>무기 다중 보급</span><small>10개 신호 동시 해제</small><em>1,000 🪙</em></button><button class="crate-open-button armor-open" data-open="armor"><i>Ⅰ</i><span>장비 보급</span><small>단일 신호 해제</small><em>100 🪙</em></button><button class="crate-open-button armor-open ten" data-open="armor10"><i>×10</i><span>장비 다중 보급</span><small>10개 신호 동시 해제</small><em>1,000 🪙</em></button><button id="arsenal-probability">등급 신호표</button><div id="arsenal-probability-panel" class="hidden"><b>장비 등급 확률 · 기존과 동일</b><span>일반 58% · 희귀 25% · 영웅 11% · 전설 5% · 신화 1%</span><small>고급 보급 추적 시스템은 향후 보장 기능을 위해 준비되어 있으며, 현재 확률은 변경하지 않습니다.</small></div>';
  document.querySelector('#shop .probability')?.insertAdjacentElement('afterend',controls);controls.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>arsenalOpenCrate(b.dataset.open.replace('10',''),b.dataset.open.endsWith('10')?10:1));controls.querySelector('#arsenal-probability').onclick=()=>controls.querySelector('#arsenal-probability-panel').classList.toggle('hidden');}
function arsenalOpenCrate(kind,count=1){if(kind==='operative')return;const cost=100*count,output=document.querySelector('#shop-result');if(wallet<cost){output.textContent=`코인이 ${cost-wallet}개 부족합니다.`;return}const list=kind==='weapon'?weapons:armors,results=Array.from({length:count},()=>rollItem(list)),highest=results.reduce((best,item)=>['common','rare','hero','legend','mythic'].indexOf(item.tier)>['common','rare','hero','legend','mythic'].indexOf(best.tier)?item:best,results[0]);wallet-=cost;renderCoins();const before=new Set(inventory.map(i=>i.name));let overlay=document.querySelector('#arsenal-opening');if(!overlay){overlay=document.createElement('div');overlay.id='arsenal-opening';document.body.append(overlay)}let done=false;const reveal=()=>{if(done)return;done=true;inventory.push(...results);for(const item of results)recordDiscovery(item);saveGear();drawGear();overlay.classList.add('hidden');const label=highest.tier==='mythic'?'MYTHIC SIGNAL':highest.tier==='legend'?'LEGENDARY':'SUPPLY OPENED';output.innerHTML=`<b class="crate-result-title ${highest.tier}">${label}</b><div class="crate-results">${results.map(item=>`<article class="loot-texture ${item.tier}"><span>${arsenalIcon(item)||itemIcon(item)}</span><b>${item.name}</b><small>${ARSENAL_TIER_LABEL[item.tier]}${before.has(item.name)?' · 중복 보유 +1':' · NEW!'}</small></article>`).join('')}</div>`};overlay.className=`opening ${highest.tier}`;overlay.innerHTML=`<div class="opening-crate ${kind}"><i></i><b>${kind==='weapon'?'⚔':'🛡'}</b></div><strong>${highest.tier==='mythic'?'신호 동기화 중…':highest.tier==='legend'?'금색 신호 감지…':'보급 상자 해제 중…'}</strong><button>건너뛰기</button>`;overlay.classList.remove('hidden');overlay.querySelector('button').onclick=reveal;setTimeout(reveal,highest.tier==='mythic'?2200:1700)}
function installOriginalArsenal(){
  decorateOriginalWeapons();
  const coreWeaponAttack=weaponAttack;weaponAttack=function(dt){const w=arsenalWeapon();if(!w)return coreWeaponAttack(dt);if(!run||paused||!player)return;const dx=(keys.KeyD?1:0)-(keys.KeyA?1:0)+touchMove.x,dy=(keys.KeyS?1:0)-(keys.KeyW?1:0)+touchMove.y;if(dx||dy)movementAim=Math.atan2(dy,dx);player.angle=movementAim;weaponState.cool-=dt;if(weaponState.cool>0)return;arsenalFire(w,dt);weaponState.cool=arsenalStat(w).cooldown};
  const coreBegin=begin;begin=function(){arsenalWorld.entities.length=0;arsenalWorld.links=[];arsenalWorld.drones=[];arsenalWorld.mirrors=[];arsenalWorld.sawWanted=arsenalWorld.mirrorWanted=0;coreBegin();const w=arsenalWeapon();if(w){player.weaponLevels||={};if(!player.weaponLevels[w.name])player.weaponLevels[w.name]=1;player.weaponEvolved=false;pop(`${w.name} 장착 · 1성 전투 시작`)}};
  const coreEnd=end;end=function(...args){arsenalWorld.entities.length=0;arsenalWorld.links=[];arsenalWorld.drones=[];arsenalWorld.mirrors=[];return coreEnd.apply(this,args)};
  const coreLevelUp=levelUp;levelUp=function(){coreLevelUp();const w=arsenalWeapon();if(!w||!run||(arsenalLevel(w)>=5&&arsenalEvolved()))return;const list=ui.upList;if(list.children.length>=3)list.lastElementChild.remove();list.prepend(arsenalCard(w));};
  const coreKillEnemy=killEnemy;killEnemy=function(e){if(e?._arsenalWire&&arsenalWorld.wire?.evolved){for(const other of enemies)if(other!==e&&Math.hypot(other.x-e.x,other.y-e.y)<92)hurt(other,arsenalWorld.wire.damage*1.5);burst(e.x,e.y,'#60faff',12)}return coreKillEnemy(e)};
  const oldDrawGear=drawGear;drawGear=function(){oldDrawGear();renderWeaponAnalysis();document.querySelectorAll('#inventory .item').forEach(button=>{const item=inventory[+button.dataset.item];if(item?.slot==='weapon'){button.title='장착 후 무기 분석에서 상세 능력치를 확인하세요.';button.ondblclick=()=>openWeaponDetail(item)}})};
  const oldItemIcon=itemIcon;itemIcon=function(item){return arsenalIcon(item)||oldItemIcon(item)};
  buy=(kind)=>arsenalOpenCrate(kind,1);document.querySelector('#buy-weapon').onclick=()=>arsenalOpenCrate('weapon',1);document.querySelector('#buy-armor').onclick=()=>arsenalOpenCrate('armor',1);
  addCrateDecor();drawGear();
}
setTimeout(installOriginalArsenal,0);requestAnimationFrame(arsenalDraw);
