// 생존자 기지: 시설을 올리되 전투에는 세 시설만 선택해서 가져간다.
let baseRestored=Number(localStorage.neonBaseRestored||0);
let baseUpgrades=JSON.parse(localStorage.neonBaseUpgrades||'{"workshop":0,"medbay":0,"engine":0,"relay":0}');
let baseLoadout=JSON.parse(localStorage.neonBaseLoadout||'["workshop","medbay","engine"]');
const baseProjects=[['🛠','드론 정비소','폭주 드론을 해체해 기지의 전력을 복구합니다.'],['🔥','용암 발전기','용암 에너지를 안전한 전력으로 바꿉니다.'],['🌃','네온 상점가','생존자들이 다시 모이는 밝은 거리입니다.'],['⛺','사막 급수소','황혼 사막에서 가져온 물로 휴식 구역을 엽니다.'],['❄','온열 대피소','빙결 기지 생존자들을 위한 따뜻한 쉼터입니다.'],['🌿','정화 온실','독성 늪지 식물을 정화해 작은 정원을 만듭니다.'],['🛰','통신 관제실','멀리 흩어진 생존자 신호를 수신합니다.'],['📚','기록 전시관','보스 도감과 균열 기록을 보관합니다.'],['⚙','제조 작업장','복구된 부품으로 기지의 불빛을 늘립니다.'],['✨','희망 광장','모든 지역 생존자를 위한 네온 축제 광장입니다.']];
const facilities={workshop:{icon:'🔧',name:'무기 정비소',desc:'무기 공격력 +4% / 레벨',apply:(p,l)=>p.damage*=1+l*.04},medbay:{icon:'✚',name:'의무실',desc:'최대 HP +8 / 레벨',apply:(p,l)=>{p.maxHp+=l*8;p.hp+=l*8}},engine:{icon:'⚡',name:'추진 엔진실',desc:'이동 속도 +4% / 레벨',apply:(p,l)=>p.speed*=1+l*.04},relay:{icon:'📡',name:'통신 중계소',desc:'맵 클리어 코인 +15 / 레벨',apply:(p,l)=>runBonus+=l*15}};
function saveBase(){localStorage.neonBaseUpgrades=JSON.stringify(baseUpgrades);localStorage.neonBaseLoadout=JSON.stringify(baseLoadout)}
function upgradeCost(id){return 100*(baseUpgrades[id]+1)}
function renderBase(){const progress=$('#base-progress'),list=$('#base-projects'),upgrades=$('#base-upgrades');if(!progress||!list||!upgrades)return;const restored=Math.min(baseRestored,baseProjects.length);progress.textContent=`복구 진행도 ${restored} / ${baseProjects.length} · 활성 시설 ${baseLoadout.length} / 3`;upgrades.innerHTML=Object.entries(facilities).map(([id,facility])=>{const level=baseUpgrades[id],active=baseLoadout.includes(id),cost=upgradeCost(id);return `<article class="facility-card ${active?'active':''}"><span class="facility-icon">${facility.icon}</span><b>${facility.name} LV.${level}/5</b><small>${facility.desc}</small><button data-upgrade="${id}" ${level>=5?'disabled':''}>${level>=5?'최대 레벨':`강화 ${cost} 🪙`}</button><button class="equip" data-equip="${id}">${active?'활성 해제':'전투에 활성화'}</button></article>`}).join('');list.innerHTML=baseProjects.map((project,index)=>{const done=index<restored;return `<article class="base-project ${done?'done':''}"><span class="base-icon">${done?project[0]:'🔒'}</span><b>${done?project[1]:'미확인 구역'}</b><small>${done?project[2]:`${index+1}번째 맵을 처음 클리어하면 복구됩니다.`}</small></article>`}).join('');upgrades.querySelectorAll('[data-upgrade]').forEach(button=>button.onclick=()=>{const id=button.dataset.upgrade,cost=upgradeCost(id);if(wallet<cost){pop('코인이 부족합니다.');return}wallet-=cost;baseUpgrades[id]++;localStorage.neonCoins=wallet;saveBase();renderCoins();renderBase();pop(`${facilities[id].name} 강화 완료!`)});upgrades.querySelectorAll('[data-equip]').forEach(button=>button.onclick=()=>{const id=button.dataset.equip,index=baseLoadout.indexOf(id);if(index>=0)baseLoadout.splice(index,1);else{if(baseLoadout.length>=3){pop('전투에는 시설을 최대 3개만 활성화할 수 있습니다.');return}baseLoadout.push(id)}saveBase();renderBase()})}
$('#base-button').onclick=()=>{renderBase();$('#menu').classList.add('hidden');$('#base').classList.remove('hidden')};
const originalEnd=end;
end=function(win=false){if(win){const next=Math.max(baseRestored,selected+1);if(next>baseRestored){baseRestored=next;localStorage.neonBaseRestored=String(baseRestored)}}return originalEnd(win)};
const originalBegin=begin;
begin=function(){originalBegin();for(const id of baseLoadout){const level=baseUpgrades[id]||0;if(level)facilities[id].apply(player,level)}if(baseLoadout.some(id=>baseUpgrades[id]))pop(`기지 지원 적용: ${baseLoadout.filter(id=>baseUpgrades[id]).map(id=>facilities[id].name).join(' · ')}`)};
$('#retry-button').onclick=begin;
// 초반은 그대로 두고, 후반 지역만 기지 성장에 맞게 조금 더 강하게 만든다.
const originalSpawnEnemy=spawnEnemy;
spawnEnemy=function(isBoss=false){const previousThreat=stageThreat;stageThreat*=1+selected*.02;originalSpawnEnemy(isBoss);stageThreat=previousThreat};
renderBase();
